### ISSUE TITLE
Add pre-commit with basic hooks

### ISSUE THREAD

**Issue by ezeBalsamo** [ezeBalsamo/Digimon-Card-Game#68]
This will be the configuration
```yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-toml
      - id: check-yaml
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: name-tests-test
        args: [--pytest-test-first]
        exclude: assertions/
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.10.1
    hooks:
      - id: pyupgrade

```
